### ISSUE TITLE
AccordionBox title bar not always clickable

### ISSUE THREAD

**Issue by zepumph** [phetsims/sun#676]
From https://github.com/phetsims/collision-lab/issues/195 and perhaps https://github.com/phetsims/ratio-and-proportion/issues/88. The RaP issue makes it seem like it was fixed, but perhaps it has regressed. Over to @jessegreenberg, let me see if it will help.

This should block any sim that supports pan/zoom with an accordion box.

**Comment by zepumph** [comment]
https://github.com/phetsims/ratio-and-proportion/issues/328 may be a helpful bread crumb, as it notes that having scenery Node's pickability listener fire eagerly changes to behavior of the clickability of the title bar. Perhaps this isn't related to pan/zoom though.

**Comment by arouinfar** [comment]
Something weird is going on, and in discussion with @jessegreenberg it doesn't seem like a pan/zoom problem. I *thought* that `supportsPanAndZoom=false` fixed the issue in circuit-construction-kit-dc, but it doesn't actually.

Steps to reproduce in cck-dc
1. Open sim, select Intro screen (this screen doesn't have the AccordionBox)
2. Click Lab screen icon in navbar
3. The AccordionBox title is not pickable
4. Reload browser tab, select Lab screen
5. The AccordionBox title is now pickable

When I tested with `supportsPanAndZoom=false`, I was essentially following steps 4 & 5.

**Comment by arouinfar** [comment]
I naively tested the same process in states-of-matter-basics which is also a two-screen sim with a single AccordionBox on the 2nd screen. The cck-dc procedure of Home Screen > Screen 2 does not result in a pickable AccordionBox title.

**Comment by jessegreenberg** [comment]
The related scenery issue and related comments for the ratio-and-proportion issue mentioned above were https://github.com/phetsims/scenery/issues/1056#issuecomment-661277631.

But I don't think this issue is related to pan and zoom. I am seeing this issue in collision-lab, CCK:DC, and gas-properties with/without the `?supportsPanAndZoom=false`.

But there are input cases where this issue goes away. See @arouinfar's example above. Also, in cck-dc, if you get to the broken state using @arouinfar's steps, if you use two fingers to pinch the screen the problem goes away. THis is true regardless of whether pan and zoom is enabled.

**Comment by arouinfar** [comment]
> @arouinfar's steps, if you use two fingers to pinch the screen the problem goes away. THis is true regardless of whether pan and zoom is enabled.

This didn't work for me.

<details><summary>Troubleshooting info</summary>

Name: Circuit Construction Kit: DC
URL: https://bayes.colorado.edu/dev/phettest/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?ea&brand=phet
Version: 1.2.0-dev.10 (unbuilt)
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1417x1329
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
@arouinfar that seems to only be true in CCK:DC. Are you not able to get it to happen in that sim?

**Comment by arouinfar** [comment]
> @arouinfar that seems to only be true in CCK:DC. Are you not able to get it to happen in that sim?

No, when I used pinch-to-zoom on my trackpad, the cursor over the AccordionBox remained an arrow. 

However, if I click anywhere within the empty play area, the AccordionBox title becomes pickable again. I also tried clicking on a UI element like a checkbox or voltmeter, but that didn't change the pikcability of the AccordionBox title.

**Comment by arouinfar** [comment]
Note that clicking in empty space doesn't fix things in other sims, like gas-properties.

**Comment by jessegreenberg** [comment]
The behavior is different in https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.0-dev.10/phet/circuit-construction-kit-dc_all_phet.html (build date 1/5/21). You cannot click the AccordionBox title the first time you click it, but all subsequent clicks work.

**Comment by zepumph** [comment]
https://github.com/phetsims/ratio-and-proportion/issues/328 makes me wonder if this is a bug with how pickable is implemented and as it pertains to the Node structure in AccordionBox. I'm not really sure how though.

**Comment by samreid** [comment]
If you click in the play area first, then mouse over the accordion box next, it is clickable.

**Comment by samreid** [comment]
This did seem similar to the Carousel problem in https://github.com/phetsims/sun/issues/672, I set pickable: false on a few occluding components and it seemed to correct the problem.  I tested in CCK-DC Lab screen.  I discovered that @zepumph identified this solution in https://github.com/phetsims/ratio-and-proportion/issues/328#issuecomment-752289947. @zepumph can you please review?

**Comment by arouinfar** [comment]
@samreid things still aren't behaving quite right.

Here's  a recording from Gas Properties in master (pulled all and cleared cache before recording). There are 5 AccordionBoxes on the Energy screen, and they all behave differently.
https://drive.google.com/file/d/1-C30Vj2_gWaVANPvDgguiNBs26d0QAgd/view?usp=sharing

| AccordionBox | ExpandCollapseButton | Title |
| --- | --- | --- |
| Average Speed | not pickable | not pickable | 
| Speed | pickable | not pickable |
| Kinetic Energy | pickable | not pickable |
| Particles | pickable | pickable, but only below the text |
| Injection Temperature | pickable | pickable |

**Troubleshooting Info**
Name: Gas Properties
URL: https://bayes.colorado.edu/dev/phettest/gas-properties/gas-properties_en.html?ea&brand=phet
Version: 1.1.0-dev.3 (unbuilt)
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 864x567
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
Keeping the changes in AccordionBox, if I additionally comment out these 2 lines in EnergyScreenView.js, all of the accordion boxes on the screen seem to work properly.

```js
    // Rendering order
    this.addChild( leftPanels );
    // leftPanels.moveToBack();
    this.addChild( rightPanels );
    // rightPanels.moveToBack();
```

@pixelzoom is the author of that file, so I'll add him as an assignee.  Maybe he can figure out why those `moveToBack` are causing problems (is something invisible occluding the accordion boxes), or make it unnecessary to call those `moveToBack` at all.

**Comment by pixelzoom** [comment]
I'll take a look at Gas Properties sometime next week.

But in the meantime, the change that @samreid made in 7f6b09a will crash with AccordionBox defaults. You added `this.titleNode.pickable = false` at a point where `titleNode` may still be `null` (the default).    Fixed in the above commit. @samreid please review.

**Comment by samreid** [comment]
Oops, I committed that 22 minutes ago, but I think I failed to push.  Thanks for the review!

![image](https://user-images.githubusercontent.com/679486/105453046-a3277f80-5c3c-11eb-9f5d-dd6f27b83806.png)

**Comment by pixelzoom** [comment]
Re the moveToBack calls... EnergyScreenView is a subclass of IdealGasLawScreenView, and is adding additional UI components. Those moveToBack calls are required to ensure that those addition UI components (panels, specifically) are behind components that need to be in the foreground, like the stopwatch.

And I'm seeing bigger problems on macOS 10.13.6 + Chrome 88.0.4324.96 + Safari 13.1.2 + Firefox 84.0.2.  Many of the UI components on various screens are not responsive at all --- checkboxes, radio buttons, combo boxes, ...

**Comment by samreid** [comment]
I'm also seeing the checkboxes are unclickable on my Mac/Chrome with the `moveToBack` calls.  If I comment out the `moveToBack` calls, then the checkboxes are clickable.  I looked for some invisible node occluding them, but didn't see anything obvious.  But I did see the IdealGasLawContainerNode extends to the left--I wonder if it occluded some of the controls on the left?

![image](https://user-images.githubusercontent.com/679486/105454158-a58ad900-5c3e-11eb-971d-c3bd8205bc2b.png)

**Comment by pixelzoom** [comment]
I'm seeing the same problems on macOS 11.1 with all browsers.  These UI components are unresponsive:

Ideal screen:
* all of the "Hold Constant" radio buttons

Explore screen
* thermometer combo box
* all of the checkboxes

Energy Screen
* Average Speed accordion box expand/collapse button
* Particles accordion box expand/collapse button
* Checkboxes in the Speed accordion box
* handle on the top of the box
* checkboxes in the top-right panel
* thermometer combo box

**Comment by pixelzoom** [comment]
All of the things that are unresponsive seem to be in the top part of the screen.

**Comment by samreid** [comment]
I'd like to alert you to another recent problem that seems related, in https://github.com/phetsims/sun/issues/672.  Carousels recently started getting input events occluded for unknown reasons (and with no changes to Carousel).  They may have a similar underlying cause in scenery.

**Comment by pixelzoom** [comment]
> But I did see the IdealGasLawContainerNode extends to the left--I wonder if it occluded some of the controls on the left?

How would that explain all of the controls to the right that don't work? Or the fact that this was working fine for a long long time?

**Comment by samreid** [comment]
No idea, like I said:

> I looked for some invisible node occluding them, but didn't see anything obvious.

Just pointed out the container node bounds were not as I expected--not sure if that is at all related to the problem at hand.

**Comment by samreid** [comment]
This patch makes many (all?) problems go away:

```diff
Index: js/common/view/IdealGasLawParticleSystemNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/IdealGasLawParticleSystemNode.js b/js/common/view/IdealGasLawParticleSystemNode.js
--- a/js/common/view/IdealGasLawParticleSystemNode.js	(revision 42c468a30122c271d853dc47d28a7ee06b7f20e2)
+++ b/js/common/view/IdealGasLawParticleSystemNode.js	(date 1611296747017)
@@ -77,7 +77,8 @@
     } );
 
     super( {
-      children: [ insideParticlesNode, outsideParticlesNode ]
+      children: [ insideParticlesNode, outsideParticlesNode ],
+      pickable: false
     } );
 
     // @private
```

**Comment by pixelzoom** [comment]
What you're seeing is the bounds where particles may be drawn.  This was recently changed -- @jonathanolson convinced me to switch from CanvasNode to Sprites.

**Comment by pixelzoom** [comment]
I reverted to a876535219709444eef057857fc895afaba29ae3, the commit before the change to Sprites. Then replaced Utils.toFixed with Number.toFixed so the sim would run.  All of the problems with UI components go away.  

Time to get @jonathanolson involved.

**Comment by samreid** [comment]
There is a commit to Sprites.js on July 13, 2020 https://github.com/phetsims/scenery/commit/c9041b5a8509ca0d41b0ec59fd3d70337e1b58f1 

> Sprite improvements (hit testing, input integration with PressListener), see https://github.com/phetsims/scenery/issues/990 Jonathan Olson 7/13/20, 3:44 PM

It relates to hit testing and input integration.  Was that around the time this stopped working?

**Comment by pixelzoom** [comment]
Tracking how this affects gas-properties in https://github.com/phetsims/gas-properties/issues/190, assigned to @jonathanolson with high priority.

**Comment by pixelzoom** [comment]
> This patch makes many (all?) problems go away:

IdealGasLawParticleSystemNode is not the only subclass of Sprites.  Rather than patching gas-properties, let's pause until @jonathanolson can be consulted.

**Comment by pixelzoom** [comment]
A reasonable fix for gas-properties was commited in the above commit. More explanation in https://github.com/phetsims/gas-properties/issues/190#issuecomment-765184864.

But none of this seems to explain the problems with AccordionBox in Collision Lab and RaP.

**Comment by samreid** [comment]
Maybe Collision Lab and Ratio and Proportions were corrected in https://github.com/phetsims/sun/commit/7f6b09a6a6b4d0c327abd7da38e987404ba38bc5, they seem to be working in master at the moment from what I can see.

**Comment by arouinfar** [comment]
I've tested a few sims out in master, and some AccordionBoxes are totally fine (Density, Collision Lab, CCK: DC). Others are still showing some weird behavior, for example: 

[Energy Skate Park](https://bayes.colorado.edu/dev/phettest/energy-skate-park/energy-skate-park_en.html?ea&brand=phet)
* Intro & Playground screens: The bar graph icon in the title of the AccordionBox is pickable in latest, but not in master.
![image](https://user-images.githubusercontent.com/8419308/105524108-6d19e800-5c9c-11eb-9af6-2adbc3052655.png)
* Graphs Screen: When hovering over the title area of the Energy Graph AccordionBox, the cursor is a hand, but the title is not actually pickable. In latest, the title is not pickable, but that was a deliberate decision due to the other UI components in the title area.
![image](https://user-images.githubusercontent.com/8419308/105524063-61c6bc80-5c9c-11eb-8ead-7ea23f180cf4.png)

[Equality Explorer](https://bayes.colorado.edu/dev/phettest/equality-explorer/equality-explorer_en.html?ea&brand=phet)
* Similar to the ESP Graphs Screen issue above, the "Equation or Inequality" and "Variable" AccordionBoxes are displaying a hand cursor when hovering near the top of the expanded box, but it's not actually pickable.  In latest, the title areas are not pickable when expanded (probably because the titles are hidden).

[Vector Addition](https://bayes.colorado.edu/dev/phettest/vector-addition/vector-addition_en.html?ea&brand=phet)
* Equations screen: I'm not sure if the Vector Values and Equation panels are AccordionBoxes or just ExpandCollapseButtons on a static panel (their size doesn't change when expaded/collapsed). That said, only the ExpandCollapseButton should be pickable. In master, the hand cursor shows up when hovering over any part of the collapsed menu or the empty space of an expanded menu.
![image](https://user-images.githubusercontent.com/8419308/105527746-5629c480-5ca1-11eb-8c02-956682946af7.png)
![image](https://user-images.githubusercontent.com/8419308/105527713-4ca05c80-5ca1-11eb-829c-1c4b8ffce86f.png)
 


It seems like there might be an issue with AccordionBoxes that do not have pickable titles by design. The cursor will sometimes turn into a hand when hovering over something non-pickable.

**Comment by samreid** [comment]
> Rather than patching gas-properties, let's pause until @jonathanolson can be consulted.

That sounds best, self-unassigning for now.

**Comment by zepumph** [comment]
In addition, it seems like this should likely not just block accordion boxes, but could be more general. Let's block everything until we understand The problem better.

**Comment by jessegreenberg** [comment]
I think this started happening after https://github.com/phetsims/ratio-and-proportion/issues/282, but not sure yet if there is anything wrong with the commit there. I found this by reverting https://github.com/phetsims/sun/commit/7f6b09a6a6b4d0c327abd7da38e987404ba38bc5 locally for testing and stepping through Picker.recursiveHitTest when clicking the MomentaDiagramAccordionBox of collision lab. The listener added in https://github.com/phetsims/ratio-and-proportion/issues/282 makes the ScreenView's Picker marked as "selfInclusive" for hit testing and changes behavior. 

Here is a much simplified example for the scenery playground, that matches what is happening in AccordionBox:

```js
var parentView = new scenery.Node();
scene.addChild( parentView );

var blueRect = new scenery.Rectangle( 25, 25, 150, 150, { fill: 'skyblue' } );
var pinkRect = new scenery.Rectangle( 40, 40, 80, 80, { fill: 'pink' } );
var exampleText = new scenery.Text( 'Testing', { center: pinkRect.center } );
parentView.addChild( blueRect );
parentView.addChild( pinkRect );
parentView.addChild( exampleText );

blueRect.addInputListener( { down: () => console.log( 'Down on blueRect!' ) } )
parentView.addInputListener( { down: () => { console.log( 'Down on parentView!' ) } } )
```
![capture (1)](https://user-images.githubusercontent.com/6396244/105562778-9a40b780-5ce9-11eb-8084-783c85302be0.png)

Click on the blue rectangle, see both:
> Down on blueRect!
> Down on parentView!

Click on the pink rectangle or text, only see:
> Down on parentView!

Remove the listener from the parentView and you will see "Down on blueRect!" if you click on any of the Nodes.

The Rectangles and Text are siblings with pickable: null, so I would have expected a hit on blueRect and parentView, even when there is an input listener on parentView.

Hope this helps @jonathanolson, removing my assignment for now.

**Comment by jonathanolson** [comment]
The commit mentioned above in https://github.com/phetsims/sun/issues/676#issuecomment-765803724 (https://github.com/phetsims/joist/commit/180efd8722f2a11aede948f4e8d5b6b769860e10) essentially makes `pickable:null` equal to `pickable:true` since every single Node under a ScreenView will have an input listener under it.

While it sounds most helpful long-term to be diligent about setting things to `pickable:false` for parts of components that shouldn't respond to input, is there a way in the short-term to not add a listener to the entire ScreenView?

**Comment by jonathanolson** [comment]
AccordionBox seems to have a lot of rectangles that when made essentially pickable:true block certain input. This is triggered by anything that adds a listener to the entire component or above (so in this case, the listener added to the view in Screen.js). As things would be buggy anytime a listener would be added to AccordionBoxes in general, I'd recommend we adjust the pickability in that type. The longer-term approaches would be good to discuss in a developer meeting.

@zepumph could the listener in https://github.com/phetsims/joist/commit/180efd8722f2a11aede948f4e8d5b6b769860e10 be changed to a Display listener? Also that doesn't seen to activate if it hits the background?

**Comment by zepumph** [comment]
See https://github.com/phetsims/joist/issues/688.

**Comment by pixelzoom** [comment]
Since gas-properties is fixed, I'm going to self-unassign.  Feel free to assign if you need more input from me.

**Comment by jonathanolson** [comment]
The commit mentioned above I believe resolves the majority of these issues. @arouinfar can you verify? (We'll leave this open to discuss at developer meeting)

**Comment by arouinfar** [comment]
@jonathanolson things look good in master.

**Comment by pixelzoom** [comment]
I'm seeing problems related to https://github.com/phetsims/sun/issues/676 in Fourier.  I have a slider track that is not getting input events when a decoration (which has no input listener) is in front of it.  I have to explicitly set pickable: false on the decoration.

Specifically...  In AmplitudeSlider.js, I have a custom slider track, inner type BarTrack.  BarTrack has invisibleTrackNode (the interactive part of the track) and visibleTrackNode (the visible bar portion, which corresponds to the amplitude).  You should be able to click (and optionally drag) anywhere on invisibleTrackNode to change the amplitude value. If I don't set `pickable: false` for visibleTrackNode, then clicking within the bounds of visibleTrackNode does nothing.

**Comment by jonathanolson** [comment]
Also, for anyone else cherry-picking things in for maintenance, do NOT cherry-pick just 361385e82e35a8a084b34d57a9d7f06ba74a85e2 (it includes a lint error, and threw a wrench in the automated process). Include the following commits in order:

- https://github.com/phetsims/joist/commit/361385e82e35a8a084b34d57a9d7f06ba74a85e2
- https://github.com/phetsims/joist/commit/c41bd915e65e6308630b823f0c0dfbf8a088dbff
- https://github.com/phetsims/joist/commit/3fa538cd809741bccffd1ab35a579f5517cfd579

**Comment by zepumph** [comment]
We discussed this today during PhET-iO meeting, we determined that this doesn't block publication of Gravity and Orbits. @jonathanolson will create an issue specific to what he wants to discuss in terms of "the future of pickability." This issue though is ready for close.
